---
# tasks file for apache2
- name: repository php56
  ansible.builtin.apt_repository: 
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: true

- name: install php5.6
  ansible.builtin.apt:
    name: php5.6
    state: present

- name: install apache2
  ansible.builtin.apt:
    name: apache2
    update_cache: true
    state: latest

- name: Install PHP module for Apache
  ansible.builtin.apt:
    name: libapache2-mod-php5.6
    state: present

- name: apache2 listen on port {{ http_port }}
  ansible.builtin.lineinfile: 
    dest: /etc/apache2/ports.conf
    regexp: "^Listen " 
    line: "Listen {{ http_port }}"
    state: present
  notify:
    - restart apache2

- name: apache2 virtualhost on port {{ http_port }}
  ansible.builtin.lineinfile: 
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: '^<VirtualHost \*:80'
    line: '<VirtualHost *:{{ http_port }}>'
  notify:
    - restart apache2
- name: apache2 copy php file on DocumentsRoot
  ansible.builtin.copy:
    src: index.php
    dest: /var/www/html/
  notify:
    - restart apache2

- name: check filename index.html
  ansible.builtin.stat:
    path: /var/www/html/index.html
  register: 
    file_stat    
- name: apache2 rename index.html to index.html.bak on DocumentsRoot
  ansible.builtin.shell:
    cmd: mv "{{ file_stat.stat.path }}" "/var/www/html/index.html.bak"
  notify:
    - restart apache2
  when: file_stat.stat.exists

- name: start apache2 on boot
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: yes

  notify:
    - restart apache2


